## Trabalhando com Matriz


* Seguem as respostas sugeridas (geralmente, existem várias maneiras de resolver um problema em Python). *

In [1]:
import numpy as np

In [7]:
a = np.array([[0, 1, 2, 3, 15.25, 6.15], [4.15, 5.65, 6.23, 7, 8.0, 81.5], [4, 5, 8.3, 7, 17.5, 20]])
a

array([[ 0.  ,  1.  ,  2.  ,  3.  , 15.25,  6.15],
       [ 4.15,  5.65,  6.23,  7.  ,  8.  , 81.5 ],
       [ 4.  ,  5.  ,  8.3 ,  7.  , 17.5 , 20.  ]])


Verifique se a dimensão que você criou está correta (use “* .shape *”)

In [8]:
a.shape

(3, 6)


Substitua o 5º elemento da 2ª linha por 19,75.

In [9]:
a[1,4] = 19.75
a

array([[ 0.  ,  1.  ,  2.  ,  3.  , 15.25,  6.15],
       [ 4.15,  5.65,  6.23,  7.  , 19.75, 81.5 ],
       [ 4.  ,  5.  ,  8.3 ,  7.  , 17.5 , 20.  ]])


Extraia a 2ª e a 3ª linha da matriz que você criou.

In [10]:
a[1]

array([ 4.15,  5.65,  6.23,  7.  , 19.75, 81.5 ])

In [11]:
a[2]

array([ 4. ,  5. ,  8.3,  7. , 17.5, 20. ])